package MiniProjetApp;

/**
* MiniProjetApp/MiniProjetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MiniProjet.idl
* jeudi 24 décembre 2020 17 h 21 WAT
*/

public final class MiniProjetHolder implements org.omg.CORBA.portable.Streamable
{
  public MiniProjetApp.MiniProjet value = null;

  public MiniProjetHolder ()
  {
  }

  public MiniProjetHolder (MiniProjetApp.MiniProjet initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MiniProjetApp.MiniProjetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MiniProjetApp.MiniProjetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MiniProjetApp.MiniProjetHelper.type ();
  }

}
