package MiniProjetApp;


/**
* MiniProjetApp/MiniProjetOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MiniProjet.idl
* jeudi 24 d�cembre 2020 17 h 21 WAT
*/

public interface MiniProjetOperations 
{
  double kmh_to_m(double kilometers);
  double celsius_to_fahrenheit(double celsius);
  double fahrenheit_to_celsius(double fahrenheit);
  void shutdown();
} // interface MiniProjetOperations
