package MiniProjetApp;


/**
* MiniProjetApp/MiniProjet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MiniProjet.idl
* jeudi 24 décembre 2020 18 h 10 WAT
*/

public interface MiniProjet extends MiniProjetOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MiniProjet
