package MiniProjetApp;


/**
* MiniProjetApp/MiniProjetPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MiniProjet.idl
* jeudi 24 décembre 2020 18 h 10 WAT
*/

public abstract class MiniProjetPOA extends org.omg.PortableServer.Servant
 implements MiniProjetApp.MiniProjetOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("kmh_to_m", new java.lang.Integer (0));
    _methods.put ("celsius_to_fahrenheit", new java.lang.Integer (1));
    _methods.put ("fahrenheit_to_celsius", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MiniProjetApp/MiniProjet/kmh_to_m
       {
         double kilometers = in.read_double ();
         double $result = (double)0;
         $result = this.kmh_to_m (kilometers);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // MiniProjetApp/MiniProjet/celsius_to_fahrenheit
       {
         double celsius = in.read_double ();
         double $result = (double)0;
         $result = this.celsius_to_fahrenheit (celsius);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // MiniProjetApp/MiniProjet/fahrenheit_to_celsius
       {
         double fahrenheit = in.read_double ();
         double $result = (double)0;
         $result = this.fahrenheit_to_celsius (fahrenheit);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // MiniProjetApp/MiniProjet/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MiniProjetApp/MiniProjet:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MiniProjet _this() 
  {
    return MiniProjetHelper.narrow(
    super._this_object());
  }

  public MiniProjet _this(org.omg.CORBA.ORB orb) 
  {
    return MiniProjetHelper.narrow(
    super._this_object(orb));
  }


} // class MiniProjetPOA
